# Generated by Django 4.1.2 on 2022-10-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.user')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.student')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.user')),
            ],
        ),
        migrations.CreateModel(
            name='CrowdCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees_count', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FaceRecognition.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_absent', models.BooleanField(default=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.student')),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FaceRecognition.instructor'),
        ),
    ]
