# Generated by Django 4.1.2 on 2022-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0003_alter_absence_table_alter_course_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
