# Generated by Django 4.1.2 on 2022-12-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0005_alter_user_options_remove_absence_section_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
