# Generated by Django 4.1.2 on 2022-12-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0006_student_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEncodings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.student')),
            ],
        ),
    ]
