# Generated by Django 4.1.2 on 2022-12-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0007_imageencodings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
