# Generated by Django 4.1.2 on 2022-12-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0008_attendeesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_encoded',
            field=models.BooleanField(default=False),
        ),
    ]
